# This workflow will build a Java project with Maven and create release
# author: https://github.com/itning

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Hugo
      uses: chabad360/hugo-actions@master
      with:
        args: --minify
