# This workflow will build a project with Hugo and public Tencent COS
# author: https://github.com/itning

name: Auto Build

#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Hugo
      uses: chabad360/hugo-actions@master
      with:
        args: --minify
    - name: Upload COS
      uses: zkqiang/tencent-cos-action@v0.1.0
      with:
        args: delete -r -f / && upload -r ./public/ /
        secret_id: ${{ secrets.SECRET_ID }}
        secret_key: ${{ secrets.SECRET_KEY }}
        bucket: ${{ secrets.BUCKET }}
        region: ap-beijing
